[general]
import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
padding = { x = 5, y = 5}
dynamic_padding = true
option_as_alt = "Both"

[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
size = 18
offset = { x = 1, y = 2 }

[keyboard]
bindings = [
    # tmux commands (Ctrl-s prefix)
    { key = "t", mods = "Command", chars = "\u0013c" }, # new window
    { key = "w", mods = "Command", chars = "\u0013x" }, # close pane
    { key = "d", mods = "Command", chars = "\u0013%" }, # left/right split
    { key = "d", mods = "Command|Shift", chars = "\u0013\"" }, # up/down split
    { key = "s", mods = "Command", chars = "\u0013s" }, # change session
    { key = "1", mods = "Command", chars = "\u00131" }, # jump to window number
    { key = "2", mods = "Command", chars = "\u00132" },
    { key = "3", mods = "Command", chars = "\u00133" },
    { key = "4", mods = "Command", chars = "\u00134" },
    { key = "5", mods = "Command", chars = "\u00135" },
    { key = "6", mods = "Command", chars = "\u00136" },
    { key = "7", mods = "Command", chars = "\u00137" },
    { key = "8", mods = "Command", chars = "\u00138" },
    { key = "9", mods = "Command", chars = "\u00139" }
]
